### PR TITLE
Have doubleclick on tray toggle visibility

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by midenok** [comment]
@TingPing Why did you close your pull requests?

**Comment by TingPing** [comment]
This patch is *11 years old*, until today the project died on Mar 16, 2012.

Feel free to revive any work I did back then, I didn't delete anything.

**Comment by midenok** [comment]
Thanks, but 11 years or 111 years means nothing to bytes. Just in case you wanted to impress me with "11 years", you didn't. That is stupid to add time factor to any decision.

**Comment by TingPing** [comment]
I meant I lost interest in it. You don't have to be so rude.

**Pull request closed without merging**
